module.exports = {
	important: true,
	content: [
		"./pages/**/*.{js,ts,jsx,tsx}",
		"./src/components/**/**/*.{ts,tsx}",
		"./src/pages/**/*.{ts,tsx}",
	],
	theme: {
		extend: {
			colors: {
				"primary-default": "#ffd951",
				"secondary-dark": "#FFB801",
				"primary-light": "#FFF1C3",
				"primary-dark": "#FFEEB4",
				"primary-tint": "#FFFDF4",
				"primary-through": "rgba(255, 217, 81, 0.3)",
				"text-primary": "#515151",
				"text-dark": "#333333",
				"text-light": "#8b8b8b",
				"text-tint": "#d1d1d1",
				"text-line": "#dddddd",
				"text-tag-blue": "#2586F9",
				"text-tag-red": "#F8979b",
				"text-tag-yellow": "#FFD951",
				"error-primary": "#E74346",
				"error-dark": "#b82a2d",
				"error-light": "#e4797e",
				"error-tint": "#FFC7C9",
				"warning-primary": "#F7A74D",
				"warning-dark": "#FFD951",
				"warning-light": "#FACB90",
				"matching-primary": "#49BD58",
				"matching-dark": "#009024",
				"matching-light": "#C2F1C7",
				"hover-gray-bg": "rgba(209, 209, 209, 0.2)",
				"bottom-shadow": "rgba(0, 0, 0, 0.05)",
				"item-favorite": "#FF5050",
				"modal-bg": "rgba(0, 0, 0, 0.67)",
				"map-bg": "rgba(255, 255, 255, 0.8)",
				"item-hover": "#EEEEEE",
			},
			fontFamily: {
				Roboto: ["Roboto", "serif"],
				RobotoThin: ["Roboto Regular"],
				RobotoBold: ["Roboto Bold"],
				rubik: ["Rubik"],
				rubikBold: ["Rubik Bold"],
				NotoSansKR: ["Noto Sans KR", "sans-serif"],
			},
			screens: {
				desktop: "1120px",
        tablet:'768px',
			},
			gridTemplateColumns: {
				"listpage-desktop": "269px minmax(1fr, 835px)",
			},
		},
	},
	plugins: [
		// require("@tailwindcss/line-clamp"),
		// require("tailwind-scrollbar-hide"),
	],
};
